[package]
name = "postgresql-rust"
version = "0.1.0"
edition = "2024"
default-run = "postgresql-rust"

[dependencies]
dotenv = "0.15.0"
openssl = "0.10.72"
tokio = {version = "1", features=["full"]}
postgres-openssl = "0.5.1"
tokio-postgres = "0.7.13"
bytes = "1.10.1"
